sudo: required

language:
    - java

jdk:
    - oraclejdk8

env:
  global:
    - secure: "BpWs9OL+KxAWZvo9D7KnpxKDGYZmYAYuPBOqxnZ4Tm2TAvy27erTIVi94bN8k0Ucw1dGEojMKtIsvEVzJZL/E1+oFba2jjXsfBL5LSCo/U+14SzagAgG6ZUq5/RsE3IL6XFrXUS41E/qAIhQS1/l076nYjXvWeYj/d2iaw7C1ro="
    - secure: "p++0n6ZneaRVrR03IQ4+xlhd632yeyTNbyKtSEOV39oWZQTNrVQjCKQG/0E4H3S5XIbSdquwTJGCnC/ld/DmD0uDAamCZcRiJf5TGhFwfgq+SXECdnh60KhSbtSmmOjb9JDaghaEQRQ8oxPS9PMCWcL9kLirWvQySGWQ0Y6EFZw="

script:
   - mvn -Phudson clean install site
