sudo: required

language:
    - java

jdk:
    - oraclejdk8

env:
  global:
    - secure: "NoqdZ2RJkOlL3CuOehKeCman4n5n5VfdiolFIB2eEr2p6nL7BJqUJJs6rpSqqnGPFMfa6s/vo/pCdC0RjcMCfBcdiUlIRcyU8u1x42tp6/oico6VnbuTN4GVi+wDFFmtcTqwPGbKYOjRgyDai1ufUMXmVvKE+e1raLU4HiA3TOw="
    - secure: "jHvQe+LLZhh3meCKGXTRqoK7J9dVyTKBrNhFwqfYeTvryfGlBhUHpgssNwBt3VQHelM2mtKEIomLrgANCA2WSTUJJQcLXeWcSHiaUJpFt21BOyNMRA+wHwihRnejTrNOupHmC3A97F9M7Qk3THGwitXPS+4kujRPidOsMBa/6sI="

script:
   - mvn -Phudson clean install site
